apiVersion: v1
kind: Pod
metadata:
  name: mcas-server
  #annotations:
  #   k8s.v1.cni.cncf.io/networks: macvlan-conf
  labels:
          app: rdma
spec:
  hostNetwork: true
  restartPolicy: OnFailure
  containers:
  - image: res-mcas-docker-local.artifactory.swg-devops.com/mcas.ubuntu18:latest
    name: mcas
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        rdma/hca: 1
  imagePullSecrets:
  - name: regcred
