apiVersion: v1
kind: Pod
metadata:
  name: mofed-test-pod
  #  annotations:
  #    k8s.v1.cni.cncf.io/networks: macvlan-conf-1
  labels:
      app: rdma
spec:
  hostNetwork: true
  restartPolicy: OnFailure
  nodeName: kivati4
  containers:
  - image: res-mcas-docker-local.artifactory.swg-devops.com/ofed-ubuntu18:latest
    name: mofed-test-ctr
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        rdma/hca: 1
    command:
        - sh
        - -c
        - |
          ibdev2netdev
          ibv_devinfo
          sleep 1000000
  imagePullSecrets:
  - name: regcred


---
apiVersion: v1
kind: Pod
metadata:
  name: mofed-test-pod-1
  #  annotations:
  #    k8s.v1.cni.cncf.io/networks: macvlan-conf-1
  labels:
      app: rdma
spec:
  hostNetwork: true
  restartPolicy: OnFailure
  nodeName: kivati4
  containers:
  - image: res-mcas-docker-local.artifactory.swg-devops.com/ofed-ubuntu18:latest
    name: mofed-test-ctr
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        rdma/hca: 1
    command:
        - sh
        - -c
        - |
          ibdev2netdev
          ibv_devinfo
          sleep 1000000
  imagePullSecrets:
  - name: regcred
